# Generated by Django 6.0.8 on 2026-08-31 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_match_match_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('summary', models.JSONField(default=dict)),
                ('content', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='matches.match')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
    ]
