# Generated by Django 6.0.8 on 2026-08-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=10)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='competitions.fixture')),
            ],
            options={
                'ordering': ['fixture__round_number', 'fixture__leg', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('YELLOW_CARD', 'Yellow card'), ('RED_CARD', 'Red card'), ('SUBSTITUTION', 'Substitution')], max_length=20)),
                ('minute', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_events', to='competitions.player')),
                ('related_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitution_events_in', to='competitions.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_events', to='competitions.team')),
            ],
            options={
                'ordering': ['minute', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'LIVE', 'FINISHED', 'CANCELLED', 'POSTPONED'])), name='valid_match_status'),
        ),
        migrations.AddConstraint(
            model_name='matchevent',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 180)), name='match_event_minute_between_one_and_180'),
        ),
        migrations.AddConstraint(
            model_name='matchevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['GOAL', 'YELLOW_CARD', 'RED_CARD', 'SUBSTITUTION'])), name='valid_match_event_type'),
        ),
    ]
