# Generated by Django 6.0.8 on 2026-08-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_fixture'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='match_status_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'event_type'], name='event_match_type_idx'),
        ),
    ]
