# Generated by Django 6.0.8 on 2026-08-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='organizations.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='competitions.league')),
            ],
            options={
                'ordering': ['-start_date', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_teams', to='competitions.season')),
            ],
            options={
                'ordering': ['season_id', 'team__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('is_captain', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='competitions.player')),
                ('season_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='competitions.seasonteam')),
            ],
            options={
                'ordering': ['season_team_id', 'shirt_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_appearances', to='competitions.team'),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_league_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('league', 'name'), name='unique_season_name_per_league'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='season_end_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='rosterentry',
            constraint=models.UniqueConstraint(fields=('season_team', 'player'), name='unique_player_per_season_team'),
        ),
        migrations.AddConstraint(
            model_name='rosterentry',
            constraint=models.UniqueConstraint(condition=models.Q(('shirt_number__isnull', False)), fields=('season_team', 'shirt_number'), name='unique_shirt_number_per_season_team'),
        ),
        migrations.AddConstraint(
            model_name='rosterentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_captain', True)), fields=('season_team',), name='one_captain_per_season_team'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_team_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='seasonteam',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_team_per_season'),
        ),
    ]
