# Generated by Django 6.0.8 on 2026-08-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField()),
                ('leg', models.PositiveSmallIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='competitions.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='competitions.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competitions.season')),
            ],
            options={
                'ordering': ['season_id', 'round_number', 'leg', 'id'],
                'constraints': [models.UniqueConstraint(fields=('season', 'home_team', 'away_team'), name='unique_fixture_direction_per_season'), models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='fixture_home_and_away_must_differ'), models.CheckConstraint(condition=models.Q(('leg__in', [1, 2])), name='fixture_leg_must_be_one_or_two')],
            },
        ),
    ]
